#!/usr/bin/env perl
use 5.18.0;
use warnings;

binmode *STDOUT, ':encoding(UTF-8)';
binmode *STDERR, ':encoding(UTF-8)';

use DateTime;
use DateTime::Format::Strptime;
use Getopt::Long::Descriptive;
use List::AllUtils qw(part);
use LWP::UserAgent;
use String::ShellQuote;
use Term::ReadKey ();
use Time::Duration::Parse;
use YAML::XS ();

use lib '/Users/rjbs/fm/code/LP-Tools/lib';
use CliM8::Util qw(activityloop matesay);
use CliM8::HTTP;

use lib 'lib';
require RJBS::CodeReview;

our $http = CliM8::HTTP->new;

$|++;

my @orig_argv = @ARGV;

my ($opt, $usage) = describe_options(
  '%c %o',
  [ 'rebuild'      => "rebuild the YAML file that holds state" ],
  [ 'project|p=s'  => "project to mark reviewed"               ],
  [ 'message|m=s'  => "commit message"                         ],
  [ 'pauseid=s'    => "your PAUSE id",  { default => uc $ENV{USER} } ],
  [ 'githubid=s'   => "your GitHub id", { default =>    $ENV{USER} } ],
  [ 'tmux!'        => 'ensure running under tmux', { default => 1 } ],
  [ 'local-cpan=s' => "where's your local cpan?", { default =>
      "$ENV{HOME}/minicpan/modules/02packages.details.txt.gz" },
  ]
);

die "--message without --rebuild or --project is nonsensical"
  if $opt->message and not ($opt->rebuild or $opt->project);

if ($opt->tmux && ! $ENV{TMUX}) {
  exec {'tmux'} 'tmux', 'new-session', '-n', 'code-review', "$^X $0 " . shell_quote(@ARGV);
  die "Tried to exec tmux but we're still here.  What?!\n";
}

my $mate = RJBS::CodeReview->new({
  http_agent => $http,
  github_id  => $opt->githubid,
});

my $res = $http->do_request(
  uri      => 'https://fastapi.metacpan.org/release/latest_by_author/RJBS',
  m8_label => "consulting MetaCPAN",
)->get;

die "Can't get latest CPAN releases" unless $res->is_success;
my $releases = $mate->decode_json_res($res);

my %is_tracked = map {; $_ => scalar(($mate->_state->{$_}{review} // '') ne 'never') }
                 keys $mate->_state->%*;

our %dist;

DIST: for my $d ($releases->{releases}->@*) {
  my $name = $d->{distribution};
  next if $name eq 'perl';

  $is_tracked{$name} = 1 unless exists $is_tracked{$name};
  $dist{ $name } = $d;
}

our @projects = grep {; $is_tracked{$_} } keys %is_tracked;

my $strp = DateTime::Format::Strptime->new(
  pattern   => '%F',
  locale    => 'en_US',
  time_zone => 'local',
);

my ($undue, $due) = part {
  return 0 unless my $rev = $mate->_state->{$_}{'review-every'};
  die "can't parse duration $rev\n" unless my $dur = parse_duration($rev);
  return 1 if ! $mate->_state->{$_}{'last-review'};
  my $last_done = $strp->parse_datetime($mate->_state->{$_}{'last-review'})->epoch;
  return 1 if time - $last_done > $dur;
  return 0;
} @projects;

@projects = (@{ $due // [] }, sort {
  ($mate->_state->{$a}{'last-review'} // '0') cmp ($mate->_state->{$b}{'last-review'} // 0)
  ||
  fc $a cmp fc $b
} @$undue);

if (@ARGV) {
  my @missing = grep {; ! ($is_tracked{$_} or $mate->_state->{$_}) } @ARGV;
  die "these projects that you asked about are unknown: @missing\n"
    if @missing;
  @projects = @ARGV;
}

if (my $project = $opt->project) {
  die "project $project is not tracked\n" unless $is_tracked{ $project };
  $mate->_state->{$project}{'last-review'}
    = DateTime->now(time_zone => 'local')->format_cldr('yyyy-MM-dd');
}

if ($opt->project) {
  do_review($opt->project, $opt->message);
  exit;
} elsif ($opt->rebuild) {
  do_review(undef, $opt->message);
  exit;
}

activityloop($mate->activity(boot => { projects => \@projects }));

say q{};
matesay("Good job reviewing!");

exit;

